export const startupLoginHTML = () => `<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:;" />
<title>JW Drama</title>
<style>
:root{color-scheme:light;font-family:"Segoe UI","Microsoft YaHei",sans-serif}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}body{background:#eef3fb;color:#14213d;user-select:none}
.shell{position:relative;width:100%;height:100%;display:flex;align-items:center;justify-content:center;padding:28px;background:radial-gradient(circle at 18% 18%,rgba(95,136,255,.24),transparent 34%),radial-gradient(circle at 84% 82%,rgba(53,199,145,.18),transparent 28%),linear-gradient(145deg,#f8fbff 0%,#eef3fb 52%,#e9f0fb 100%)}
.shell:before{content:"";position:absolute;inset:-45%;background:conic-gradient(from 90deg,transparent,rgba(91,134,255,.12),transparent 28%);animation:spin 9s linear infinite;pointer-events:none}
.window-actions{position:absolute;right:14px;top:12px;z-index:5;-webkit-app-region:no-drag}.close{width:32px;height:32px;border:0;border-radius:10px;background:rgba(255,255,255,.62);color:#50607a;font-size:20px;line-height:1;cursor:pointer}.close:hover{background:#fff;color:#0f172a}
.drag{position:absolute;left:0;right:56px;top:0;height:42px;-webkit-app-region:drag}
.splash{position:absolute;inset:0;z-index:4;display:flex;flex-direction:column;align-items:center;justify-content:center;background:radial-gradient(circle at 50% 38%,rgba(102,126,255,.24),transparent 34%),linear-gradient(145deg,#f9fbff 0%,#eef3fb 58%,#e8eef9 100%);opacity:1;transform:scale(1);transition:opacity .48s ease,transform .62s cubic-bezier(.2,.8,.2,1);pointer-events:auto}
body.splash-out .splash{opacity:0;transform:scale(1.075);pointer-events:none}
.splash-mark{position:relative;width:142px;height:142px;border-radius:42px;display:grid;place-items:center;background:linear-gradient(145deg,#4d7cff,#6958f0);box-shadow:0 30px 70px rgba(77,124,255,.34);opacity:0;transform:scale(.48) rotate(-12deg);animation:splashLogo .9s cubic-bezier(.16,1,.3,1) .1s forwards}
.splash-mark:before{content:"";position:absolute;inset:-22px;border-radius:54px;border:2px solid rgba(88,120,255,.22);animation:pulseRing 1.5s ease-out .45s infinite}
.splash-mark svg{width:82px;height:82px;filter:drop-shadow(0 9px 16px rgba(20,34,68,.18))}
.splash-name{margin-top:30px;font-size:30px;font-weight:760;letter-spacing:.35px;opacity:0;transform:translateY(18px);animation:splashText .55s ease .58s forwards}
.splash-sub{margin-top:9px;color:#6d7b92;font-size:13px;font-weight:650;letter-spacing:2.6px;opacity:0;animation:splashText .45s ease .82s forwards}
.splash-progress{width:188px;height:4px;margin-top:34px;border-radius:999px;background:rgba(105,124,165,.14);overflow:hidden;opacity:0;animation:fadeIn .28s ease .92s forwards}.splash-progress span{display:block;width:0;height:100%;border-radius:inherit;background:linear-gradient(90deg,#4d7cff,#715cf6);animation:progress 1.75s cubic-bezier(.2,.75,.2,1) 1s forwards}
.card{position:relative;z-index:2;width:100%;max-width:430px;padding:34px 34px 30px;border:1px solid rgba(255,255,255,.78);border-radius:26px;background:rgba(255,255,255,.86);box-shadow:0 28px 80px rgba(60,80,120,.18),inset 0 1px 0 rgba(255,255,255,.9);backdrop-filter:blur(22px);opacity:0;transform:translateY(34px) scale(.97);pointer-events:none;transition:opacity .5s ease,transform .62s cubic-bezier(.16,1,.3,1)}
body.login-ready .card{opacity:1;transform:translateY(0) scale(1);pointer-events:auto}
.brand{display:flex;flex-direction:column;align-items:center;text-align:center}.logo{width:82px;height:82px;border-radius:24px;display:grid;place-items:center;background:linear-gradient(145deg,#4d7cff,#6d5dfc);box-shadow:0 18px 36px rgba(77,124,255,.28)}.logo svg{width:47px;height:47px;filter:drop-shadow(0 5px 8px rgba(20,34,68,.16))}.name{margin-top:20px;font-size:24px;font-weight:700;letter-spacing:.2px}.sub{margin-top:7px;color:#7a879c;font-size:13px;letter-spacing:1.4px}
.divider{height:1px;margin:27px 0 23px;background:linear-gradient(90deg,transparent,#dce4f1,transparent)}.title{font-size:15px;font-weight:650}.field{margin-top:17px}.label{display:block;margin-bottom:7px;color:#5f6c80;font-size:12px;font-weight:600}.input-wrap{position:relative}.input{width:100%;height:46px;border:1px solid #dbe3ef;border-radius:13px;background:#f8faff;padding:0 14px;font-size:14px;color:#16213c;outline:none;transition:border-color .18s,box-shadow .18s,background .18s}.input:focus{border-color:#7596ff;background:#fff;box-shadow:0 0 0 4px rgba(87,129,255,.11)}.input.password{padding-right:48px}.eye{position:absolute;right:8px;top:7px;width:34px;height:32px;border:0;border-radius:9px;background:transparent;color:#8793a6;cursor:pointer}.eye:hover{background:#edf2fa;color:#4a5a74}
.submit{width:100%;height:47px;margin-top:23px;border:0;border-radius:14px;background:linear-gradient(135deg,#4d7cff,#6558ef);color:#fff;font-size:14px;font-weight:700;cursor:pointer;box-shadow:0 12px 25px rgba(81,112,244,.22);transition:transform .16s,box-shadow .16s,opacity .16s}.submit:hover{transform:translateY(-1px);box-shadow:0 16px 30px rgba(81,112,244,.28)}.submit:active{transform:translateY(0)}.submit:disabled{opacity:.68;cursor:default;transform:none}.status{min-height:20px;margin-top:12px;text-align:center;font-size:12px;color:#d34d5c}.status.ok{color:#1f9d72}
@keyframes spin{to{transform:rotate(360deg)}}@keyframes splashLogo{0%{opacity:0;transform:scale(.48) rotate(-12deg)}62%{opacity:1;transform:scale(1.09) rotate(2deg)}100%{opacity:1;transform:scale(1) rotate(0)}}@keyframes splashText{to{opacity:1;transform:translateY(0)}}@keyframes fadeIn{to{opacity:1}}@keyframes progress{0%{width:0}72%{width:84%}100%{width:100%}}@keyframes pulseRing{0%{opacity:.75;transform:scale(.82)}100%{opacity:0;transform:scale(1.34)}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}.splash-mark,.splash-name,.splash-sub,.splash-progress{opacity:1!important;transform:none!important}.splash-progress span{width:100%}.card{opacity:1;transform:none;pointer-events:auto}.splash{display:none}}
</style>
</head>
<body>
<div class="shell">
  <div class="drag"></div><div class="window-actions"><button class="close" id="close" aria-label="关闭">×</button></div>
  <section class="splash" aria-label="启动画面"><div class="splash-mark" aria-hidden="true"><svg viewBox="0 0 64 64" fill="none"><path d="M32 8c-8.2 0-14.8 6.6-14.8 14.8 0 .6 0 1.2.1 1.8A11.5 11.5 0 0 0 22.7 46H29v8h-7.5a2.5 2.5 0 0 0 0 5h21a2.5 2.5 0 0 0 0-5H35v-8h6.3a11.5 11.5 0 0 0 5.4-21.4c.1-.6.1-1.2.1-1.8C46.8 14.6 40.2 8 32 8Z" fill="white" fill-opacity=".96"/><path d="M32 23v23M32 34l-8-7M32 38l8-8" stroke="#5A67F2" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="splash-name">JW Drama</div><div class="splash-sub">AI DRAMA WORKSPACE</div><div class="splash-progress" aria-hidden="true"><span></span></div></section>
  <main class="card"><section class="brand"><div class="logo" aria-hidden="true"><svg viewBox="0 0 64 64" fill="none"><path d="M32 8c-8.2 0-14.8 6.6-14.8 14.8 0 .6 0 1.2.1 1.8A11.5 11.5 0 0 0 22.7 46H29v8h-7.5a2.5 2.5 0 0 0 0 5h21a2.5 2.5 0 0 0 0-5H35v-8h6.3a11.5 11.5 0 0 0 5.4-21.4c.1-.6.1-1.2.1-1.8C46.8 14.6 40.2 8 32 8Z" fill="white" fill-opacity=".95"/><path d="M32 23v23M32 34l-8-7M32 38l8-8" stroke="#5A67F2" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="name">JW Drama</div><div class="sub">AI DRAMA WORKSPACE</div></section>
  <div class="divider"></div><div class="title">账号登录</div><form id="login-form" autocomplete="off"><div class="field"><label class="label" for="username">账号</label><div class="input-wrap"><input class="input" id="username" name="username" value="admin" spellcheck="false" /></div></div><div class="field"><label class="label" for="password">密码</label><div class="input-wrap"><input class="input password" id="password" name="password" type="password" autocomplete="current-password" autofocus /><button class="eye" id="toggle-password" type="button" aria-label="显示密码">◉</button></div></div><button class="submit" id="submit" type="submit">登录并进入工作台</button><div class="status" id="status" role="status" aria-live="polite"></div></form></main>
</div>
<script>
const form=document.getElementById('login-form'),password=document.getElementById('password'),submit=document.getElementById('submit'),status=document.getElementById('status'),toggle=document.getElementById('toggle-password');let animationStarted=false;
const startAnimation=()=>{if(animationStarted||document.visibilityState!=='visible')return;animationStarted=true;setTimeout(()=>document.body.classList.add('splash-out'),2850);setTimeout(()=>{document.body.classList.add('login-ready');password.focus()},3280)};document.addEventListener('visibilitychange',startAnimation);window.addEventListener('focus',startAnimation);startAnimation();
document.getElementById('close').addEventListener('click',()=>window.close());toggle.addEventListener('click',()=>{const visible=password.type==='text';password.type=visible?'password':'text';toggle.setAttribute('aria-label',visible?'显示密码':'隐藏密码');password.focus()});
form.addEventListener('submit',async(event)=>{event.preventDefault();if(submit.disabled)return;status.className='status';status.textContent='';submit.disabled=true;submit.textContent='正在验证…';try{const result=await window.mediagoDesktop?.authenticateStartup?.({username:document.getElementById('username').value,password:password.value});if(!result?.ok){status.textContent=result?.message||'账号或密码错误';password.select();return}status.className='status ok';status.textContent='登录成功，正在进入工作台…';submit.textContent='正在启动…';setTimeout(()=>window.close(),420)}catch{status.textContent='登录服务暂不可用，请重试'}finally{if(!status.classList.contains('ok')){submit.disabled=false;submit.textContent='登录并进入工作台'}}});
</script></body></html>`;
